export const cars = [
    {
      id: 1,
      name: "Toyota Corolla",
      brand: "Toyota",
      manufacturedYear: 2019,
      doors: 4,
      price: 22000,
      available: "yes",
      image: "toyota-corrolla.png",
    },
    {
      id: 2,
      name: "Honda Civic",
      brand: "Honda",
      manufacturedYear: 2020,
      doors: 4,
      price: 25000,
      available: "yes",
      image: "honda-civic-1.6-automatik-slika-231511286.png",
    },
    {
      id: 3,
      name: "Ford Mustang",
      brand: "Ford",
      manufacturedYear: 2018,
      doors: 2,
      price: 35000,
      available: "no",
      image: "Ford_Mustang_2025_101A_PYZ_882_89W_13A_CON_64F_99H_44U_EBST_DEFAULT_EXT_4.png",
    },
    {
      id: 4,
      name: "BMW 3 Series",
      brand: "BMW",
      manufacturedYear: 2021,
      doors: 4,
      price: 45000,
      available: "yes",
      image: "BMW-3-Series-Exterior-167583.png",
    },
    {
      id: 5,
      name: "Chevrolet Camaro",
      brand: "Chevrolet",
      manufacturedYear: 2017,
      doors: 2,
      price: 32000,
      available: "no",
      image: "2024-chevrolet-camaro-ss-collectors-edition-1-647e1933c6c20.png",
    },
    {
      id: 6,
      name: "Audi A4",
      brand: "Audi",
      manufacturedYear: 2022,
      doors: 4,
      price: 42000,
      available: "yes",
      image: "audi-a4.png",
    },
    {
      id: 7,
      name: "Mercedes-Benz E-Class",
      brand: "Mercedes-Benz",
      manufacturedYear: 2020,
      doors: 4,
      price: 50000,
      available: "yes",
      image: "mercedesEclass.png",
    },
    {
      id: 8,
      name: "Lexus IS",
      brand: "Lexus",
      manufacturedYear: 2019,
      doors: 4,
      price: 38000,
      available: "no",
      image: "lexus.png",
    },
    {
      id: 9,
      name: "Volkswagen Golf",
      brand: "Volkswagen",
      manufacturedYear: 2021,
      doors: 4,
      price: 28000,
      available: "yes",
      image: "golf 7r.png",
    },
    {
      id: 10,
      name: "Subaru Outback",
      brand: "Subaru",
      manufacturedYear: 2022,
      doors: 4,
      price: 32000,
      available: "yes",
      image: "subaruOutback.png",
    },
  ];